name: Deploy Angular
on:
    workflow_call:
        inputs:
            host:
                required: true
                type: string
            base-href:
                required: true
                type: string
            project-name:
                required: true
                type: string

jobs:
    deploy-angular:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3

            - name: Install Dependencies
              run: npm i

            - name: Build
              run: npm run build -- --base-href=${{ inputs.base-href }}

            - name: Move Built Files to Corresponding Folder
              run: |
                  rm -rf /var/www/${{ inputs.host }}/html${{ inputs.base-href }}
                  mkdir -p /var/www/${{ inputs.host }}/html${{ inputs.base-href }}
                  mv dist/${{ inputs.project-name }}/* /var/www/${{ inputs.host }}/html${{ inputs.base-href }}
