name: Deploy Next.js
on:
    workflow_call:
        inputs:
            process-name:
                required: true
                type: string

jobs:
    deploy-nextjs:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3

            - name: Get Current Working Directory
              run: pwd

            - name: Get Current User
              run: whoami

            - name: Get pm2 Location
              run: which pm2

            - name: Get pm2 Status
              run: pm2 status

            - name: Get Running Processes
              run: pm2 list
#            - name: Install Dependencies
#              run: npm i
#
#            - name: Build
#              run: npm run build
#
#            - name: Delete Previous Process Silently
#              continue-on-error: true
#              run: pm2 delete "${{ inputs.process-name }}"
#
#            - name: Start a New Process
#              run: pm2 start npm --name "${{ inputs.process-name }}" -- start
#
#            - name: Save Current Process List
#              run: pm2 save
