name: Deploy Docusaurus
on:
  workflow_call:
    inputs:
      host:
        required: true
        type: string
      base-href:
        required: true
        type: string

jobs:
  deploy-docusaurus:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Remove Previous Deploy Folder
        run: rm -rf /var/www/${{ inputs.host }}/html${{ inputs.base-href }}

      - name: Create Deploy Folder
        run: mkdir -p /var/www/${{ inputs.host }}/html${{ inputs.base-href }}

      - name: Move Built Files to Deploy Folder
        run: mv build/* /var/www/${{ inputs.host }}/html${{ inputs.base-href }}
