name: Deploy Qwik
on:
    workflow_call:
        inputs:
            process-name:
                required: true
                type: string

jobs:
    deploy-qwik:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3

            - name: Install Dependencies
              run: npm i

            - name: Build
              run: npm run build

            - name: Delete Previous Process Silently
              continue-on-error: true
              run: pm2 delete "${{ inputs.process-name }}"

            - name: Start a New Process
              run: pm2 start server/entry.express.js --name ${{ inputs.process-name }}

            - name: Save Current Process List
              run: pm2 save
